package com.cdweb.be.enums;

public enum NotificationType {
    MATCH_JOINED,
    MATCH_LEFT,
    MATCH_CANCELLED,
    MATCH_RESUMED,
    MATCH_REJECTED,
    MATCH_COMMENT,
    SYSTEM,
    NEW_MESSAGE,
    BILL_CREATED,
    BILL_PAID,
    BILL_CONFIRMED,
    MATCH_REVIEW_REQUEST,
    FRIEND_REQUEST,
    FRIEND_ACCEPTED,
    ACCOUNT_BANNED,
    ACCOUNT_UNBANNED
}
